#!/bin/sh

# This file is part of the docker-registry-self-signed project, which
# is distributed under the terms of the MIT License, See the project's
# LICENSE file for details.
#
# Copyright (C) 2020 Allan Young

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        # Our post-install simply runs update-ca-certificates to
        # update certificates.
        update-ca-certificates
        ;;
     *)
        # Not expected to get here.
        echo "postinst called with unexpected argument: $1"
        exit 0
        ;;
esac
exit 0
